# Generated by Django 5.0.2 on 2024-06-09 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Category_name', models.CharField(max_length=200, verbose_name='Category name')),
                ('Category_image', models.ImageField(upload_to='category_images/', verbose_name='Category image')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50, verbose_name='Product name')),
                ('Product_description', models.TextField(verbose_name='Product description')),
                ('Product_regular_price', models.FloatField(verbose_name='Regular price $')),
                ('Product_sale_price', models.FloatField(verbose_name='Sale price $')),
                ('Sale_price_time_end', models.DateTimeField(verbose_name='Sale price time end')),
                ('Product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('ProductImage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProductImage_image', models.ImageField(upload_to='products_images/')),
                ('ProductImage_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
