# Generated by Django 5.0.2 on 2024-06-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='ProductImage_image',
            new_name='ProductImage',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='ProductImage_product',
            new_name='product',
        ),
    ]
