# Generated by Django 5.0.2 on 2024-06-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productimage_image_productimages_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Product_regular_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_sale_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Sale_price_time_end',
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Size')),
                ('Product_regular_price', models.FloatField(verbose_name='Regular price $')),
                ('Product_sale_price', models.FloatField(verbose_name='Sale price $')),
                ('Sale_price_time_end', models.DateTimeField(verbose_name='Sale price time end')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.products')),
            ],
        ),
    ]
