# Generated by Django 5.0.2 on 2024-06-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_product_regular_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SKU',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N/A'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='ProductImage',
            field=models.ImageField(upload_to='products_images/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='Product_sale_price',
            field=models.FloatField(default=0, verbose_name='Sale price $'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='Sale_price_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sale price time end'),
        ),
    ]
