# Generated by Django 5.0.2 on 2024-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_category_image_alter_products_sku_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_ourproducts',
            options={'verbose_name': 'Our Products', 'verbose_name_plural': 'Our Products'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='IS_spacial_product',
            field=models.BooleanField(default=False),
        ),
    ]
