# Generated by Django 5.0.2 on 2024-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is available ?'),
        ),
    ]
