# Generated by Django 5.0.2 on 2024-06-10 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_rating',
            name='Rating_stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating stars'),
        ),
        migrations.AlterField(
            model_name='product_rating',
            name='User_Name',
            field=models.CharField(max_length=100, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='product_rating',
            name='rate_content',
            field=models.TextField(verbose_name='Rate content'),
        ),
    ]
