# Generated by Django 5.0.2 on 2024-06-17 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_rating_rating_stars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='home_ourproducts',
            options={'verbose_name': 'Our Products in Home page', 'verbose_name_plural': 'Our Products in Home page'},
        ),
        migrations.AlterModelOptions(
            name='product_rating',
            options={'verbose_name': 'Products Ratings', 'verbose_name_plural': 'Products Ratings'},
        ),
        migrations.AddField(
            model_name='products',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
