# Generated by Django 5.0.2 on 2024-06-17 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
