# Generated by Django 5.0.2 on 2024-06-19 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_rating_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
