# Generated by Django 5.0.2 on 2024-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productsize_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
