# Generated by Django 5.0.2 on 2024-06-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productsize_product_size_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='product_size_uuid',
        ),
    ]
