# Generated by Django 5.0.2 on 2024-06-19 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productsize_product_size_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_size_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
