# Generated by Django 5.0.2 on 2024-06-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_uploaded_at'),
        ('products', '0021_alter_productsize_product_size_uuid'),
    ]

    operations = [
    ]
