# Generated by Django 5.0.2 on 2024-06-18 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replaises',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Replies on Testimonials', 'verbose_name_plural': 'Replies on Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
