# Generated by Django 5.0.2 on 2024-06-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonials', '0002_alter_testimonials_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replaises',
            options={'verbose_name': 'Replies on Testimonials', 'verbose_name_plural': 'Replies on Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
