# Generated by Django 5.0.2 on 2024-06-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonials', '0003_alter_replaises_options_alter_testimonials_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replaises',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Replies on Testimonials', 'verbose_name_plural': 'Replies on Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
