# Generated by Django 5.0.2 on 2024-08-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonials', '0002_alter_replaises_options_alter_testimonials_options_and_more'),
        ('Testimonials', '0004_alter_replaises_options_alter_testimonials_options'),
    ]

    operations = [
    ]
