# Generated by Django 5.0.2 on 2024-07-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
