# Generated by Django 5.0.2 on 2024-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
