# Generated by Django 5.0.2 on 2024-08-19 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Membership Name')),
            ],
            options={
                'verbose_name': 'Memberships',
                'verbose_name_plural': 'Memberships',
            },
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.EmailField(max_length=100, verbose_name='User Email')),
                ('phone', models.CharField(max_length=100, verbose_name='User Phone Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='Members_profile_images', verbose_name='User Profile Image')),
                ('memberShip_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_MemberShip_Set', to='coffe_app.membership_model', verbose_name='User MemberShip')),
            ],
            options={
                'verbose_name': 'Members',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Notes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Notes_Set', to='coffe_app.user_model', verbose_name='User Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Bills_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='Bill_images', verbose_name='Bill Image')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Bill Amount')),
                ('data', models.DateField(auto_now=True, null=True, verbose_name='Bill created Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Bills_Set', to='coffe_app.user_model', verbose_name='User Bills')),
            ],
            options={
                'verbose_name': 'User Bills',
                'verbose_name_plural': 'User Bills',
            },
        ),
    ]
