# Generated by Django 5.0.2 on 2024-08-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0004_bills_model_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills_model',
            old_name='data',
            new_name='date',
        ),
    ]
