# Generated by Django 5.0.2 on 2024-08-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0005_rename_data_bills_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='monthly_bills_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Monthly Bills Count'),
        ),
        migrations.AddField(
            model_name='user_model',
            name='total_bills_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Bills Amount'),
        ),
        migrations.AddField(
            model_name='user_model',
            name='total_bills_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Bills Count'),
        ),
        migrations.AlterField(
            model_name='bills_model',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Bill Serial number'),
        ),
        migrations.AlterField(
            model_name='bills_model',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Bills_Set', to='coffe_app.user_model', verbose_name='User Name'),
        ),
    ]
