# Generated by Django 5.0.2 on 2024-08-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0006_user_model_monthly_bills_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='monthly_bills_count',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='total_bills_amount',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='total_bills_count',
        ),
    ]
