# Generated by Django 5.0.2 on 2024-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0008_alter_bills_model_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_qr_code_image',
            name='id',
        ),
        migrations.AddField(
            model_name='user_qr_code_image',
            name='memberShip_number',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_model',
            name='profile_image',
            field=models.ImageField(blank=True, default='defualt_profile_image.jpg', null=True, upload_to='Members_profile_images', verbose_name='User Profile Image'),
        ),
    ]
