# Generated by Django 5.0.2 on 2024-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffe_app', '0009_remove_user_qr_code_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership_model',
            name='id_card_image',
            field=models.FileField(default=1, upload_to='MemberShip_card_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_model',
            name='memberShip_number',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
