# Generated by Django 5.0.2 on 2024-07-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Shipping Flat rate', 'verbose_name_plural': 'Shipping Flat rate'},
        ),
    ]
